name: Build on Fedora ARM64

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Create directories
      run: |
        mkdir -p ${{ github.workspace }}/app/build

    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: arm64v8/centos:8
        options: -v ${{ github.workspace }}/:/app -w /app
        run: |
          dnf install -y cmake
          cd build
          cmake ..
          make
          make install

