name: Build on Fedora ARM64

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [arm64v8]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Create directories
      run: |
        mkdir -p ${{ github.workspace }}/build

    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: redhat/ubi8:8.7
        options: -v ${{ github.workspace }}/:/app -w /app
        run: |
          uname -a
          dnf update &&  dnf install -y cmake openssl-devel libaio libaio-devel automake autoconf \
                         bison libtool ncurses-devel libgcrypt-devel libev-devel \
                         libcurl-devel zlib-devel zstd vim-common procps-ng-devel
          cd build && cmake ..
          make && cpack

