name: CMake

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Depends
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: "apt update && apt install install bison pkg-config cmake devscripts debconf \
            debhelper automake bison ca-certificates libprocps-dev \
            libcurl4-openssl-dev cmake debhelper libaio-dev \
            libncurses-dev libssl-dev libtool libz-dev libgcrypt-dev libev-dev libprocps-dev \
            lsb-release build-essential rsync libdbd-mysql-perl \
            libnuma1 socat librtmp-dev libtinfo5 vim-common \
            liblz4-tool liblz4-1 liblz4-dev zstd python-docutils qpress"

    - name: Build
      # Build your program with the given configuration
      run: "cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

